name: Build source code and send to Capgo

on:
  push:
    tags:
      - '*'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        id: install_code
        run: npm ci
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build
        id: build_code
        run: npm run verify:android
  build_ios:
    runs-on: macOS-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        id: install_code
        run: npm ci
      - name: Build
        id: build_code
        run: npm run verify:ios
  deploy:
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest
    name: 'Build code and release'
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        id: install_code
        run: npm ci
      - name: Lint
        id: lint_code
        run: npm run lint
      - name: Build
        id: build_code
        run: npm run build
      - name: Verify
        id: verify_code
        run: npm run verify:web
      - uses: JS-DevTools/npm-publish@v1
        if: "!contains(github.ref, '-alpha.')"
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        if: "contains(github.ref, '-alpha.')"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
